version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: erp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: "Suji@123"
      POSTGRES_DB: erp_main
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erp_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: erp-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bisman.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./my-backend
      dockerfile: Dockerfile
    container_name: erp-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://erp_admin:Suji%40123@postgres:5432/erp_main"
      NODE_ENV: development
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data:
    name: erp_postgres_data
