#!/bin/bash
echo "==================================="
echo "RAILWAY PATH DIAGNOSTIC"
echo "==================================="
echo ""
echo "1. PROJECT ROOT:"
pwd
echo ""
echo "2. FRONTEND SERVICE (my-frontend/):"
echo "   - Dockerfile exists: $(test -f my-frontend/Dockerfile && echo "✅ YES" || echo "❌ NO")"
echo "   - railway.toml exists: $(test -f my-frontend/railway.toml && echo "✅ YES" || echo "❌ NO")"
echo "   - Dockerfile path: $(readlink -f my-frontend/Dockerfile 2>/dev/null || echo "my-frontend/Dockerfile")"
echo ""
echo "3. BACKEND SERVICE (my-backend/):"
echo "   - Dockerfile exists: $(test -f my-backend/Dockerfile && echo "✅ YES" || echo "❌ NO")"
echo "   - railway.toml exists: $(test -f my-backend/railway.toml && echo "✅ YES" || echo "❌ NO")"
echo "   - Dockerfile path: $(readlink -f my-backend/Dockerfile 2>/dev/null || echo "my-backend/Dockerfile")"
echo ""
echo "4. RAILWAY.TOML CONFIGURATIONS:"
echo ""
echo "   FRONTEND railway.toml:"
cat my-frontend/railway.toml | grep -A 1 "dockerfilePath"
echo ""
echo "   BACKEND railway.toml:"
cat my-backend/railway.toml | grep -A 1 "dockerfilePath"
echo ""
echo "5. WHERE RAILWAY LOOKS FOR FILES:"
echo "   If Root Directory = '' (empty):"
echo "      Railway looks in: /Users/abhi/Desktop/BISMAN ERP/"
echo "      Dockerfile search: ./Dockerfile (NOT FOUND ❌)"
echo ""
echo "   If Root Directory = 'my-frontend':"
echo "      Railway looks in: /Users/abhi/Desktop/BISMAN ERP/my-frontend/"
echo "      Dockerfile search: my-frontend/Dockerfile (✅ FOUND)"
echo ""
echo "==================================="
