site_name: BISMAN Living Docs
site_description: "Automated living documentation for BISMAN ERP"
site_author: "Bisman Docs Bot"
repo_url: "https://github.com/your-org/your-repo"

docs_dir: 'system-docs'
site_dir: 'system-docs-site'

nav:
  - Home: index.md
  - Pages:
      - Users List: pages/Page_Users_List.md
      - Orders Edit: pages/Page_Orders_Edit.md
  - Functions:
      - Process Payment: functions/F_Process_Payment.md
  - Schema:
      - users: schema/users.md

theme:
  name: material

plugins:
  - search
  - macros
  - i18n:
      default_language: en
      languages:
        en: English

extra:
  version: 1.0
  analytics: false
