#!/bin/bash

# Railway Manual Deploy Helper Script
# Use this when automatic deployment doesn't trigger

echo "=========================================="
echo "🚀 RAILWAY MANUAL DEPLOY"
echo "=========================================="
echo ""
echo "⚠️  Auto-deploy from 'deployment' branch not configured"
echo ""
echo "📋 Quick Fix Steps:"
echo ""
echo "1. Opening Railway Dashboard..."
echo ""

# Open Railway dashboard
railway open

echo ""
echo "2. In the browser that just opened:"
echo ""
echo "   For BACKEND Service:"
echo "   -------------------"
echo "   • Click 'bisman-ERP-Backend'"
echo "   • Click 'Settings' (⚙️ icon)"
echo "   • Find 'Branch' dropdown"
echo "   • Change to: 'deployment'"
echo "   • Click 'Save'"
echo "   • Click 'Deploy' button"
echo ""
echo "   For FRONTEND Service:"
echo "   --------------------"
echo "   • Go back to project"
echo "   • Click 'bisman-ERP-frontend'"
echo "   • Click 'Settings' (⚙️ icon)"
echo "   • Find 'Branch' dropdown"
echo "   • Change to: 'deployment'"
echo "   • Click 'Save'"
echo "   • Click 'Deploy' button"
echo ""
echo "=========================================="
echo "⏱️  Wait 5 minutes for deployment"
echo "=========================================="
echo ""
echo "✅ After deployment, verify:"
echo ""
echo "   Backend logs:"
echo "   railway logs  (select: bisman-ERP-Backend)"
echo ""
echo "   Frontend URL:"
echo "   https://bisman-erp-frontend-production.up.railway.app"
echo ""
echo "=========================================="
