// Master Module and Page Configuration
// This represents ALL available modules and pages in the system
// Enterprise Admin can assign these to Super Admins

const MASTER_MODULES = [
  {
    id: 'common',
    name: 'Common Module',
    description: 'Pages available to all users - NO ASSIGNMENT REQUIRED',
    icon: 'FiUser',
    category: 'Common',
    businessCategory: 'All',
    alwaysAccessible: true, // This module is accessible by all authenticated users
    pages: [
      { id: 'about-me', name: 'About Me', path: '/common/about-me' },
      { id: 'change-password', name: 'Change Password', path: '/common/change-password' },
      { id: 'security-settings', name: 'Security Settings', path: '/common/security-settings' },
      { id: 'notifications', name: 'Notifications', path: '/common/notifications' },
      { id: 'messages', name: 'Messages', path: '/common/messages' },
      { id: 'help-center', name: 'Help Center', path: '/common/help-center' },
      { id: 'documentation', name: 'Documentation', path: '/common/documentation' },
      { id: 'user-settings', name: 'User Settings', path: '/common/user-settings' },
    ],
  },
  {
    id: 'finance',
    name: 'Finance Module',
    description: 'Complete financial management system',
    icon: 'FiDollarSign',
    category: 'Finance',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Finance Dashboard', path: '/finance/dashboard' },
      { id: 'accounts', name: 'Accounts Management', path: '/accounts' },
      { id: 'accounts-payable', name: 'Accounts Payable', path: '/accounts-payable' },
      { id: 'accounts-receivable', name: 'Accounts Receivable Summary', path: '/finance/accounts-receivable-summary' },
      { id: 'accounts-payable-summary', name: 'Accounts Payable Summary', path: '/finance/accounts-payable-summary' },
      { id: 'general-ledger', name: 'General Ledger', path: '/finance/general-ledger' },
      { id: 'executive-dashboard', name: 'Executive Dashboard', path: '/finance/executive-dashboard' },
      { id: 'cfo-dashboard', name: 'CFO Dashboard', path: '/cfo-dashboard' },
      { id: 'finance-controller', name: 'Finance Controller', path: '/finance-controller' },
      { id: 'treasury', name: 'Treasury', path: '/treasury' },
      { id: 'banker', name: 'Banker Portal', path: '/banker' },
    ],
  },
  {
    id: 'operations',
    name: 'Operations Module',
    description: 'Operations and inventory management',
    icon: 'FiPackage',
    category: 'Operations',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Operations Dashboard', path: '/operations-manager' },
      { id: 'inventory', name: 'Inventory Management', path: '/operations/inventory-management' },
      { id: 'kpi', name: 'KPI Dashboard', path: '/operations/kpi-dashboard' },
      { id: 'hub-incharge', name: 'Hub Incharge', path: '/hub-incharge' },
      { id: 'store-incharge', name: 'Store Incharge', path: '/store-incharge' },
      { id: 'manager', name: 'Manager Portal', path: '/manager' },
      { id: 'staff', name: 'Staff Portal', path: '/staff' },
    ],
  },
  {
    id: 'hr',
    name: 'Human Resources',
    description: 'Employee, attendance, payroll, and HR operations',
    icon: 'FiUsers',
    category: 'Human Resources',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'HR Dashboard', path: '/hr' },
      { id: 'user-creation', name: 'Create New User', path: '/hr/user-creation' },
      { id: 'employees', name: 'Employees', path: '/hr/employees' },
      { id: 'attendance', name: 'Attendance', path: '/hr/attendance' },
      { id: 'leave-management', name: 'Leave Management', path: '/hr/leave-management' },
      { id: 'payroll', name: 'Payroll', path: '/hr/payroll' },
      { id: 'performance', name: 'Performance', path: '/hr/performance' },
      { id: 'recruitment', name: 'Recruitment', path: '/hr/recruitment' },
      { id: 'policies', name: 'Policies', path: '/hr/policies' },
      { id: 'training', name: 'Training', path: '/hr/training' },
    ],
  },
  {
    id: 'procurement',
    name: 'Procurement Module',
    description: 'Purchase orders and supplier management',
    icon: 'FiShoppingCart',
    category: 'Procurement',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Procurement Dashboard', path: '/procurement-officer' },
      { id: 'purchase-orders', name: 'Purchase Orders', path: '/procurement/purchase-orders' },
      { id: 'suppliers', name: 'Supplier Management', path: '/procurement/suppliers' },
      { id: 'requisitions', name: 'Purchase Requisitions', path: '/procurement/requisitions' },
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance & Legal Module',
    description: 'Legal compliance and case management',
    icon: 'FiShield',
    category: 'Compliance',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Compliance Dashboard', path: '/compliance-officer' },
      { id: 'legal', name: 'Legal Dashboard', path: '/legal' },
      { id: 'legal-cases', name: 'Legal Case Management', path: '/compliance/legal-case-management' },
      { id: 'regulations', name: 'Regulations Tracker', path: '/compliance/regulations' },
  // Agreements & Contracts (view-only)
  { id: 'legal-agreements', name: 'Agreements & Contracts', path: '/compliance/agreements' },
    ],
  },
  {
    id: 'system',
    name: 'System Administration',
    description: 'System settings, users, and configuration',
    icon: 'FiSettings',
    category: 'Administration',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'IT Admin Dashboard', path: '/it-admin' },
      { id: 'user-management', name: 'User Management', path: '/system/user-management' },
      { id: 'user-creation', name: 'User Creation', path: '/system/user-creation' },
      { id: 'roles-users', name: 'Roles & Users Report', path: '/system/roles-users-report' },
      { id: 'pages-roles', name: 'Pages & Roles Report', path: '/system/pages-roles-report' },
  { id: 'role-access-explorer', name: 'Role & Access Explorer', path: '/system/role-access-explorer' },
      { id: 'permission-manager', name: 'Permission Manager', path: '/system/permission-manager' },
      { id: 'company-setup', name: 'Company Setup', path: '/system/company-setup' },
      { id: 'system-settings', name: 'System Settings', path: '/system/system-settings' },
      { id: 'master-data', name: 'Master Data Management', path: '/system/master-data-management' },
      { id: 'integration-settings', name: 'Integration Settings', path: '/system/integration-settings' },
      { id: 'api-config', name: 'API Integration Config', path: '/system/api-integration-config' },
      { id: 'system-health', name: 'System Health Dashboard', path: '/system/system-health-dashboard' },
      { id: 'scheduler', name: 'Scheduler', path: '/system/scheduler' },
      { id: 'deployment', name: 'Deployment Tools', path: '/system/deployment-tools' },
      { id: 'backup-restore', name: 'Backup & Restore', path: '/system/backup-restore' },
      { id: 'audit-logs', name: 'Audit Logs', path: '/system/audit-logs' },
      { id: 'error-logs', name: 'Error Logs', path: '/system/error-logs' },
      { id: 'server-logs', name: 'Server Logs', path: '/system/server-logs' },
      { id: 'about-me', name: 'About Me System', path: '/system/about-me' },
    ],
  },
  {
    id: 'super-admin',
    name: 'Super Admin Module',
    description: 'Super admin tools and oversight',
    icon: 'FiShield',
    category: 'Administration',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Super Admin Dashboard', path: '/super-admin' },
      { id: 'security', name: 'Security Management', path: '/super-admin/security' },
      { id: 'system', name: 'System Overview', path: '/super-admin/system' },
      { id: 'orders', name: 'Orders Management', path: '/super-admin/orders' },
    ],
  },
  {
    id: 'admin',
    name: 'Admin Module',
    description: 'General administration',
    icon: 'FiUser',
    category: 'Administration',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Admin Dashboard', path: '/admin' },
      { id: 'users', name: 'Users Management', path: '/users' },
      { id: 'common-user-creation', name: 'Common User Creation', path: '/common/user-creation' },
    ],
  },
  {
    id: 'task-management',
    name: 'Task Management Module',
    description: 'Task tracking and management',
    icon: 'FiCheckSquare',
    category: 'Operations',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Task Dashboard', path: '/task-dashboard' },
      { id: 'my-tasks', name: 'My Tasks', path: '/task-dashboard/my-tasks' },
      { id: 'team-tasks', name: 'Team Tasks', path: '/task-dashboard/team-tasks' },
    ],
  },
  {
    id: 'chat',
    name: 'Chat & Communication',
    description: 'Real-time messaging and AIVA assistant - NO ASSIGNMENT REQUIRED',
    icon: 'FiMessageSquare',
    category: 'Communication',
    businessCategory: 'All',
    alwaysAccessible: true, // Chat is accessible by all authenticated users
    pages: [
      { id: 'chat', name: 'Chat', path: '/chat' },
      { id: 'aiva', name: 'AIVA Assistant', path: '/chat/aiva' },
      { id: 'channels', name: 'Channels', path: '/chat/channels' },
      { id: 'direct-messages', name: 'Direct Messages', path: '/chat/direct' },
    ],
  },
];

module.exports = { MASTER_MODULES };
