// Master Module and Page Configuration
// This represents ALL available modules and pages in the system
// Enterprise Admin can assign these to Super Admins

const MASTER_MODULES = [
  {
    id: 'common',
    name: 'Common Module',
    description: 'Pages available to all users - NO ASSIGNMENT REQUIRED',
    icon: 'FiUser',
    category: 'Common',
    businessCategory: 'All',
    alwaysAccessible: true, // This module is accessible by all authenticated users
    pages: [
      { id: 'about-me', name: 'About Me', path: '/common/about-me' },
      { id: 'change-password', name: 'Change Password', path: '/common/change-password' },
      { id: 'help-center', name: 'Help Center', path: '/common/help-center' },
      { id: 'user-settings', name: 'User Settings', path: '/common/user-settings' },
      { id: 'payment-request', name: 'Payment Request', path: '/common/payment-request' },
      { id: 'payment-requests-create', name: 'Create Payment Request', path: '/common/payment-requests/create' },
      { id: 'root-calendar', name: 'Calendar (Root)', path: '/calendar' },
      { id: 'dashboard', name: 'Dashboard', path: '/dashboard' },
      { id: 'access-denied', name: 'Access Denied', path: '/access-denied' },
      // Removed per request: security-settings, notifications, messages, documentation, 
      // bank-accounts, calendar (non-root), task-approvals, settings, assistant
    ],
  },
  {
    id: 'finance',
    name: 'Finance Module',
    description: 'Complete financial management system',
    icon: 'FiDollarSign',
    category: 'Finance',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'accounts', name: 'Accounts Management', path: '/accounts' },
      { id: 'accounts-payable', name: 'Accounts Payable', path: '/accounts-payable' },
      { id: 'accounts-receivable', name: 'Accounts Receivable Summary', path: '/finance/accounts-receivable-summary' },
      { id: 'accounts-payable-summary', name: 'Accounts Payable Summary', path: '/finance/accounts-payable-summary' },
      { id: 'general-ledger', name: 'General Ledger', path: '/finance/general-ledger' },
      { id: 'executive-dashboard', name: 'Executive Dashboard', path: '/finance/executive-dashboard' },
      { id: 'cfo-dashboard', name: 'CFO Dashboard', path: '/cfo-dashboard' },
      { id: 'finance-controller', name: 'Finance Controller', path: '/finance-controller' },
      // Removed per request: treasury
      { id: 'banker', name: 'Banker Portal', path: '/banker' },
    ],
  },
  {
    id: 'operations',
    name: 'Operations Module',
    description: 'Operations and inventory management',
    icon: 'FiPackage',
    category: 'Operations',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Operations Dashboard', path: '/operations-manager' },
      { id: 'inventory', name: 'Inventory Management', path: '/operations/inventory-management' },
      // Removed per request: kpi (KPI Dashboard)
      { id: 'hub-incharge', name: 'Hub Incharge', path: '/hub-incharge' },
      { id: 'store-incharge', name: 'Store Incharge', path: '/store-incharge' },
      { id: 'staff', name: 'Staff Portal', path: '/staff' },
    ],
  },
  {
    id: 'hr',
    name: 'Human Resources',
    description: 'Employee, attendance, payroll, and HR operations',
    icon: 'FiUsers',
    category: 'Human Resources',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'user-creation', name: 'Create New User', path: '/hr/user-creation' },
      { id: 'policy', name: 'HR Policy Page', path: '/hr/policy' },
      { id: 'hr-policy', name: 'HR Policy', path: '/common/hr-policy' },
    ],
  },
  {
    id: 'procurement',
    name: 'Procurement Module',
    description: 'Purchase orders and supplier management',
    icon: 'FiShoppingCart',
    category: 'Procurement',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Procurement Dashboard', path: '/procurement-officer' },
      { id: 'purchase-orders', name: 'Purchase Orders', path: '/procurement/purchase-orders' },
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance & Legal Module',
    description: 'Legal compliance and case management',
    icon: 'FiShield',
    category: 'Compliance',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Compliance Dashboard', path: '/compliance-officer' },
      { id: 'compliance-dashboard', name: 'Compliance Dashboard Alt', path: '/compliance/compliance-dashboard' },
      { id: 'legal', name: 'Legal Dashboard', path: '/legal' },
      { id: 'legal-cases', name: 'Legal Case Management', path: '/compliance/legal-case-management' },
      { id: 'legal-agreements', name: 'Agreements & Contracts', path: '/compliance/agreements' },
    ],
  },
  {
    id: 'system',
    name: 'System Administration',
    description: 'System settings, users, and configuration',
    icon: 'FiSettings',
    category: 'Administration',
    businessCategory: 'Business ERP',
    pages: [
      // Only keeping log and AI pages - other pages moved to super-admin module
      { id: 'audit-logs', name: 'Audit Logs', path: '/system/audit-logs' },
      { id: 'error-logs', name: 'Error Logs', path: '/system/error-logs' },
      { id: 'server-logs', name: 'Server Logs', path: '/system/server-logs' },
      { id: 'ai-training', name: 'AI Training', path: '/ai-training' },
    ],
  },
  {
    id: 'super-admin',
    name: 'Super Admin Module',
    description: 'Super admin tools and oversight - Can be assigned to Super Admin',
    icon: 'FiShield',
    category: 'Administration',
    businessCategory: 'Business ERP',
    // hideFromAssignment removed - now visible in Enterprise Admin allocation page
    pages: [
      { id: 'super-admin-security', name: 'Security Management', path: '/super-admin/security' },
      // System module pages (excluding AI and logs) - IDs must match page-registry.ts
      { id: 'super-admin-it-admin', name: 'IT Admin Dashboard', path: '/super-admin/system/it-admin' },
      { id: 'super-admin-user-management', name: 'Client Management', path: '/super-admin/system/user-management' },
      // Permission Manager & Modules & Roles are now part of Client Management page (hidden from sidebar)
      { id: 'super-admin-pages-roles-report', name: 'Pages & Roles Report', path: '/super-admin/system/pages-roles-report' },
      { id: 'super-admin-role-access-explorer', name: 'Role & Access Explorer', path: '/super-admin/system/role-access-explorer' },
      { id: 'super-admin-system-settings', name: 'System Settings', path: '/super-admin/system/system-settings' },
      { id: 'super-admin-integration-settings', name: 'Integration Settings', path: '/super-admin/system/integration-settings' },
      { id: 'super-admin-deployment-tools', name: 'Deployment Tools', path: '/super-admin/system/deployment-tools' },
      { id: 'super-admin-backup-restore', name: 'Backup & Restore', path: '/super-admin/system/backup-restore' },
      { id: 'super-admin-system-health', name: 'System Health', path: '/super-admin/system/system-health' },
      { id: 'super-admin-about-me', name: 'About Me', path: '/super-admin/about-me' },
    ],
  },
  {
    id: 'admin',
    name: 'Admin Module',
    description: 'General administration - Can be assigned to Admin and Super Admin users',
    icon: 'FiUser',
    category: 'Administration',
    businessCategory: 'Business ERP',
    // hideFromAssignment removed - now visible in Enterprise Admin allocation page
    pages: [
      { id: 'dashboard', name: 'Admin Dashboard', path: '/admin' },
      { id: 'admin-dashboard', name: 'Admin Dashboard Alt', path: '/admin/dashboard' },
      { id: 'users', name: 'Users Management', path: '/admin/users' },
      { id: 'clients', name: 'Clients', path: '/admin/clients' },
      { id: 'modules', name: 'Modules', path: '/admin/modules' },
      { id: 'organizations', name: 'Organizations', path: '/admin/organizations' },
      { id: 'billing', name: 'Billing', path: '/admin/billing' },
      { id: 'settings', name: 'Settings', path: '/admin/settings' },
      { id: 'reports', name: 'Reports', path: '/admin/reports' },
      { id: 'support', name: 'Support', path: '/admin/support' },
      { id: 'integrations', name: 'Integrations', path: '/admin/integrations' },
      { id: 'notifications', name: 'Notifications', path: '/admin/notifications' },
      { id: 'audit', name: 'Audit', path: '/admin/audit' },
      { id: 'permissions', name: 'Permissions', path: '/admin/permissions' },
      { id: 'developer', name: 'Developer', path: '/admin/developer' },
      { id: 'ai', name: 'AI', path: '/admin/ai' },
      { id: 'ai-analytics', name: 'AI Analytics', path: '/admin/ai-analytics' },
      { id: 'rag-sources', name: 'RAG Sources', path: '/admin/rag-sources' },
      { id: 'common-user-creation', name: 'Common User Creation', path: '/common/user-creation' },
    ],
  },
  {
    id: 'task-management',
    name: 'Task Management Module',
    description: 'Task tracking and management',
    icon: 'FiCheckSquare',
    category: 'Operations',
    businessCategory: 'Business ERP',
    pages: [
      { id: 'dashboard', name: 'Task Dashboard', path: '/task-dashboard' },
      { id: 'create-task', name: 'Create Task', path: '/tasks/create' },
    ],
  },
  {
    id: 'chat',
    name: 'Chat & Communication',
    description: 'Real-time messaging and AIVA assistant - NO ASSIGNMENT REQUIRED',
    icon: 'FiMessageSquare',
    category: 'Communication',
    businessCategory: 'All',
    alwaysAccessible: true, // Chat is accessible by all authenticated users
    pages: [
      { id: 'chat', name: 'Chat', path: '/chat' },
      { id: 'chat-ai', name: 'Chat AI', path: '/chat/ai' },
    ],
  },
  {
    id: 'enterprise-admin',
    name: 'Enterprise Admin Module',
    description: 'Enterprise-level administration and multi-tenant management - Auto-assigned to Enterprise Admin',
    icon: 'FiBriefcase',
    category: 'Enterprise',
    businessCategory: 'Enterprise',
    hideFromAssignment: true, // Don't show in module assignment UI - auto-assigned to Enterprise Admin
    pages: [
      { id: 'dashboard', name: 'Enterprise Dashboard', path: '/enterprise-admin/dashboard' },
      { id: 'modules', name: 'Module Management', path: '/enterprise-admin/modules' },
      { id: 'super-admins', name: 'Super Admins', path: '/enterprise-admin/super-admins' },
      { id: 'super-admins-create', name: 'Create Super Admin', path: '/enterprise-admin/super-admins/create' },
      { id: 'users', name: 'Users', path: '/enterprise-admin/users' },
      { id: 'organizations', name: 'Organizations', path: '/enterprise-admin/organizations' },
      { id: 'billing', name: 'Billing', path: '/enterprise-admin/billing' },
      { id: 'settings', name: 'Settings', path: '/enterprise-admin/settings' },
      { id: 'reports', name: 'Reports', path: '/enterprise-admin/reports' },
      { id: 'support', name: 'Support', path: '/enterprise-admin/support' },
      { id: 'integrations', name: 'Integrations', path: '/enterprise-admin/integrations' },
      { id: 'notifications', name: 'Notifications', path: '/enterprise-admin/notifications' },
      { id: 'audit', name: 'Audit', path: '/enterprise-admin/audit' },
      { id: 'logs', name: 'Logs', path: '/enterprise-admin/logs' },
      { id: 'activity-logs', name: 'Activity Logs', path: '/enterprise-admin/activity-logs' },
      { id: 'ai-handling', name: 'AI Handling', path: '/enterprise-admin/ai-handling' },
      { id: 'monitoring', name: 'Monitoring', path: '/enterprise-admin/monitoring' },
      { id: 'monitoring-database', name: 'Database Monitoring', path: '/enterprise-admin/monitoring/database' },
      { id: 'monitoring-performance', name: 'Performance Monitoring', path: '/enterprise-admin/monitoring/performance' },
      { id: 'monitoring-system-health', name: 'System Health', path: '/enterprise-admin/monitoring/system-health' },
    ],
  },
];

module.exports = { MASTER_MODULES };
