-- ============================================================================
-- BISMAN ERP - RBAC Default Deny Migration
-- ============================================================================
-- Purpose: Enforce DEFAULT DENY for all governed pages
-- 
-- Rules:
--   1. can_view defaults to FALSE (explicit grant required)
--   2. Adds check constraint to ensure explicit access grants
--   3. Creates helper views for RBAC auditing
-- 
-- Date: 2025-01-19
-- ============================================================================

BEGIN;

-- ============================================================================
-- STEP 1: Change can_view default to FALSE (default deny)
-- ============================================================================

-- Note: Existing rows with can_view=true are NOT affected
ALTER TABLE role_page_access 
ALTER COLUMN can_view SET DEFAULT FALSE;

COMMENT ON COLUMN role_page_access.can_view IS 'Explicit grant required. DEFAULT DENY: must be TRUE to allow access.';

-- ============================================================================
-- STEP 2: Add auto_seeded column to track auto-generated mappings
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'role_page_access' AND column_name = 'auto_seeded') THEN
        ALTER TABLE role_page_access ADD COLUMN auto_seeded BOOLEAN DEFAULT FALSE;
        COMMENT ON COLUMN role_page_access.auto_seeded IS 'TRUE if mapping was auto-generated by seeder script.';
    END IF;
END $$;

-- ============================================================================
-- STEP 3: Create view for pages missing RBAC mappings
-- ============================================================================

CREATE OR REPLACE VIEW v_pages_missing_rbac AS
SELECT 
    p.id,
    p.page_code,
    p.display_name,
    p.route,
    p.module_id,
    m.module_code,
    m.display_name as module_name,
    p.is_governed,
    p.is_active,
    p.sync_status
FROM pages_master p
LEFT JOIN modules_master m ON m.id = p.module_id
LEFT JOIN role_page_access rpa ON rpa.page_id = p.id AND rpa.can_view = TRUE
WHERE p.is_active = TRUE
  AND p.is_governed = TRUE
  AND rpa.id IS NULL
ORDER BY m.module_code, p.route;

COMMENT ON VIEW v_pages_missing_rbac IS 'Lists governed pages that have NO role access mappings (access denied to everyone).';

-- ============================================================================
-- STEP 4: Create view for RBAC coverage summary
-- ============================================================================

CREATE OR REPLACE VIEW v_rbac_coverage_summary AS
SELECT 
    m.module_code,
    m.display_name as module_name,
    COUNT(DISTINCT p.id) as total_governed_pages,
    COUNT(DISTINCT CASE WHEN rpa.id IS NOT NULL THEN p.id END) as pages_with_rbac,
    COUNT(DISTINCT CASE WHEN rpa.id IS NULL THEN p.id END) as pages_missing_rbac,
    ROUND(
        (COUNT(DISTINCT CASE WHEN rpa.id IS NOT NULL THEN p.id END)::numeric / 
         NULLIF(COUNT(DISTINCT p.id), 0)::numeric) * 100, 
        1
    ) as coverage_percent
FROM pages_master p
LEFT JOIN modules_master m ON m.id = p.module_id
LEFT JOIN role_page_access rpa ON rpa.page_id = p.id AND rpa.can_view = TRUE
WHERE p.is_active = TRUE
  AND p.is_governed = TRUE
GROUP BY m.module_code, m.display_name
ORDER BY pages_missing_rbac DESC, m.module_code;

COMMENT ON VIEW v_rbac_coverage_summary IS 'Summary of RBAC coverage by module.';

-- ============================================================================
-- STEP 5: Create function to check RBAC access
-- ============================================================================

CREATE OR REPLACE FUNCTION check_rbac_access(
    p_route TEXT,
    p_role_name VARCHAR(100)
) RETURNS TABLE (
    page_id INTEGER,
    page_code VARCHAR(100),
    is_governed BOOLEAN,
    has_access BOOLEAN,
    can_view BOOLEAN,
    can_edit BOOLEAN,
    can_delete BOOLEAN,
    can_export BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        pm.id as page_id,
        pm.page_code,
        pm.is_governed,
        CASE 
            WHEN pm.is_governed = FALSE THEN TRUE  -- Non-governed = allow
            WHEN pm.is_public = TRUE THEN TRUE     -- Public = allow
            WHEN rpa.can_view = TRUE THEN TRUE     -- Explicit grant = allow
            ELSE FALSE                              -- DEFAULT DENY
        END as has_access,
        COALESCE(rpa.can_view, FALSE) as can_view,
        COALESCE(rpa.can_edit, FALSE) as can_edit,
        COALESCE(rpa.can_delete, FALSE) as can_delete,
        COALESCE(rpa.can_export, FALSE) as can_export
    FROM pages_master pm
    LEFT JOIN role_page_access rpa ON rpa.page_id = pm.id AND rpa.role_name = p_role_name
    WHERE pm.is_active = TRUE
      AND (
          pm.route = p_route
          OR pm.route_pattern = p_route
          OR (
              pm.is_dynamic = TRUE 
              AND p_route ~ ('^' || REGEXP_REPLACE(COALESCE(pm.route_pattern, pm.route), ':[a-zA-Z_]+', '[^/]+', 'g') || '$')
          )
      )
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION check_rbac_access IS 'Check RBAC access for a route and role. Returns has_access=FALSE if no mapping exists (DEFAULT DENY).';

-- ============================================================================
-- STEP 6: Create index for faster RBAC lookups
-- ============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_role_page_access_lookup') THEN
        CREATE INDEX idx_role_page_access_lookup 
        ON role_page_access(page_id, role_name, can_view);
    END IF;
END $$;

-- ============================================================================
-- COMMIT
-- ============================================================================

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES (Run manually)
-- ============================================================================

-- Check pages missing RBAC
-- SELECT COUNT(*) FROM v_pages_missing_rbac;

-- Check coverage summary
-- SELECT * FROM v_rbac_coverage_summary;

-- Test RBAC check function
-- SELECT * FROM check_rbac_access('/admin/clients', 'SUPER_ADMIN');
