ALTER TABLE routes ADD COLUMN IF NOT EXISTS source_file VARCHAR(200);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS handler_count INT;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS middleware_count INT;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS has_params BOOLEAN;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS last_scanned_at TIMESTAMPTZ;

ALTER TABLE rbac_routes ADD COLUMN IF NOT EXISTS source_file VARCHAR(200);
ALTER TABLE rbac_routes ADD COLUMN IF NOT EXISTS handler_count INT;
ALTER TABLE rbac_routes ADD COLUMN IF NOT EXISTS middleware_count INT;
ALTER TABLE rbac_routes ADD COLUMN IF NOT EXISTS has_params BOOLEAN;
ALTER TABLE rbac_routes ADD COLUMN IF NOT EXISTS last_scanned_at TIMESTAMPTZ;