apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erp-worker
  template:
    metadata:
      labels:
        app: erp-worker
    spec:
      containers:
        - name: worker
          image: yourrepo/erp-worker:latest
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secrets
                  key: dsn
          readinessProbe:
            exec:
              command: ["/bin/sh","-c","pgrep node || exit 1"]
            initialDelaySeconds: 5
            periodSeconds: 20
