global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["localhost:3000"]
    metrics_path: /metrics

  - job_name: "worker"
    static_configs:
      - targets: ["localhost:4000"]
    metrics_path: /metrics
