/**
 * Centralized Page Registry
 * Maps all ERP pages to their routes, permissions, roles, and metadata
 * Automatically scanned to generate dynamic navigation
 */

import {
  Shield, Users, Database, Activity, Settings, Key, Server,
  DollarSign, FileText, TrendingUp, BarChart3, PieChart, Briefcase,
  ShoppingCart, Package, Truck, ClipboardCheck, FileCheck, Scale,
  AlertTriangle, BookOpen, Archive, CreditCard, Wallet, Building,
  Calculator, Receipt, Banknote, FileSpreadsheet, Landmark, Globe,
  Coins, FolderOpen, FileEdit, Upload, CheckCircle, Clock,
  Box, Boxes, ListChecks, Tag, Factory, Route, MapPin,
  Clipboard, FileSignature, Gavel, Folder, UserCheck,
  type LucideIcon
} from 'lucide-react';

// Page status types
export type PageStatus = 'active' | 'coming-soon' | 'disabled';

// Page metadata interface
export interface PageMetadata {
  id: string;
  name: string;
  path: string;
  icon: LucideIcon;
  module: 'system' | 'finance' | 'procurement' | 'operations' | 'compliance';
  permissions: string[]; // Required permissions (OR logic)
  roles: string[]; // Recommended roles
  status: PageStatus;
  description?: string;
  badge?: string; // Optional badge text (e.g., "New", "Beta")
  order?: number; // Display order within module
}

// Module metadata
export interface ModuleMetadata {
  id: string;
  name: string;
  icon: LucideIcon;
  description: string;
  color: string; // Tailwind color class
  order: number;
}

/**
 * Module Definitions
 */
export const MODULES: Record<string, ModuleMetadata> = {
  system: {
    id: 'system',
    name: 'System Administration',
    icon: Shield,
    description: 'System management and configuration',
    color: 'blue',
    order: 1,
  },
  finance: {
    id: 'finance',
    name: 'Finance & Accounting',
    icon: DollarSign,
    description: 'Financial management and reporting',
    color: 'green',
    order: 2,
  },
  procurement: {
    id: 'procurement',
    name: 'Procurement',
    icon: ShoppingCart,
    description: 'Purchase and supplier management',
    color: 'purple',
    order: 3,
  },
  operations: {
    id: 'operations',
    name: 'Operations',
    icon: Package,
    description: 'Operational workflows and inventory',
    color: 'orange',
    order: 4,
  },
  compliance: {
    id: 'compliance',
    name: 'Compliance & Legal',
    icon: Scale,
    description: 'Compliance and legal management',
    color: 'red',
    order: 5,
  },
};

/**
 * Complete Page Registry
 * All 73 pages (6 existing + 67 newly created)
 */
export const PAGE_REGISTRY: PageMetadata[] = [
  // ==================== SYSTEM MODULE (13 pages) ====================
  {
    id: 'system-settings',
    name: 'System Settings',
    path: '/system/system-settings',
    icon: Settings,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR', 'IT ADMIN'],
    status: 'active',
    description: 'Configure system-wide settings',
    order: 1,
  },
  {
    id: 'user-management',
    name: 'User Management',
    path: '/system/user-management',
    icon: Users,
    module: 'system',
    permissions: ['user-management'],
    roles: ['SUPER_ADMIN', 'ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Manage users and permissions',
    order: 2,
  },
  {
    id: 'permission-manager',
    name: 'Permission Manager',
    path: '/system/permission-manager',
    icon: Key,
    module: 'system',
    permissions: ['user-management'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Manage system permissions',
    order: 3,
  },
  {
    id: 'audit-logs',
    name: 'Audit Logs',
    path: '/system/audit-logs',
    icon: Activity,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR', 'IT ADMIN'],
    status: 'active',
    description: 'View system activity and audit trails',
    order: 4,
  },
  {
    id: 'backup-restore',
    name: 'Backup & Restore',
    path: '/system/backup-restore',
    icon: Database,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Manage system backups and restoration',
    order: 5,
  },
  {
    id: 'scheduler',
    name: 'Task Scheduler',
    path: '/system/scheduler',
    icon: Clock,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Configure automated tasks and schedules',
    order: 6,
  },
  {
    id: 'system-health',
    name: 'System Health',
    path: '/system/system-health-dashboard',
    icon: Activity,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR', 'IT ADMIN'],
    status: 'active',
    description: 'Monitor system performance and health',
    order: 7,
  },
  {
    id: 'integration-settings',
    name: 'Integration Settings',
    path: '/system/integration-settings',
    icon: Route,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Configure third-party integrations',
    order: 8,
  },
  {
    id: 'error-logs',
    name: 'Error Logs',
    path: '/system/error-logs',
    icon: AlertTriangle,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR', 'IT ADMIN'],
    status: 'active',
    description: 'View and manage system error logs',
    order: 9,
  },
  {
    id: 'server-logs',
    name: 'Server Logs',
    path: '/system/server-logs',
    icon: Server,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Access server logs and diagnostics',
    order: 10,
  },
  {
    id: 'deployment-tools',
    name: 'Deployment Tools',
    path: '/system/deployment-tools',
    icon: Upload,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Manage deployments and releases',
    order: 11,
  },
  {
    id: 'api-config',
    name: 'API Configuration',
    path: '/system/api-integration-config',
    icon: Route,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR'],
    status: 'active',
    description: 'Configure API integrations',
    order: 12,
  },
  {
    id: 'company-setup',
    name: 'Company Setup',
    path: '/system/company-setup',
    icon: Building,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'ADMIN'],
    status: 'active',
    description: 'Configure company information',
    order: 13,
  },
  {
    id: 'master-data',
    name: 'Master Data',
    path: '/system/master-data-management',
    icon: Database,
    module: 'system',
    permissions: ['system-settings'],
    roles: ['SUPER_ADMIN', 'ADMIN'],
    status: 'active',
    description: 'Manage master data entities',
    order: 14,
  },
  {
    id: 'system-about',
    name: 'About Me',
    path: '/system/about-me',
    icon: Users,
    module: 'system',
    permissions: ['system-settings', 'user-management'],
    roles: ['SUPER_ADMIN', 'SYSTEM ADMINISTRATOR', 'IT ADMIN'],
    status: 'active',
    description: 'User profile',
    order: 99,
  },

  // ==================== FINANCE MODULE (30 pages) ====================
  {
    id: 'executive-dashboard',
    name: 'Executive Dashboard',
    path: '/finance/executive-dashboard',
    icon: BarChart3,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER', 'TREASURY'],
    status: 'active',
    description: 'Executive financial overview',
    order: 1,
  },
  {
    id: 'financial-statements',
    name: 'Financial Statements',
    path: '/finance/financial-statements',
    icon: FileText,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'View comprehensive financial statements',
    order: 2,
  },
  {
    id: 'general-ledger',
    name: 'General Ledger',
    path: '/finance/general-ledger',
    icon: BookOpen,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER', 'ACCOUNTS'],
    status: 'active',
    description: 'Manage general ledger entries',
    order: 3,
  },
  {
    id: 'budgeting-forecasting',
    name: 'Budgeting & Forecasting',
    path: '/finance/budgeting-forecasting',
    icon: TrendingUp,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Create and manage budgets',
    order: 4,
  },
  {
    id: 'cash-flow-statement',
    name: 'Cash Flow Statement',
    path: '/finance/cash-flow-statement',
    icon: DollarSign,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'TREASURY'],
    status: 'active',
    description: 'View cash flow reports',
    order: 5,
  },
  {
    id: 'company-dashboard',
    name: 'Company Dashboard',
    path: '/finance/company-dashboard',
    icon: Building,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO'],
    status: 'active',
    description: 'Executive company overview',
    order: 6,
  },
  {
    id: 'period-end-closing',
    name: 'Period End Closing',
    path: '/finance/period-end-closing',
    icon: Archive,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER', 'ACCOUNTS'],
    status: 'active',
    description: 'Manage period closing process',
    order: 7,
  },
  {
    id: 'cost-center-analysis',
    name: 'Cost Center Analysis',
    path: '/finance/cost-center-analysis',
    icon: PieChart,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Analyze cost centers',
    order: 8,
  },
  {
    id: 'journal-entries-approval',
    name: 'Journal Entry Approval',
    path: '/finance/journal-entries-approval',
    icon: CheckCircle,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Approve journal entries',
    order: 9,
  },
  {
    id: 'trial-balance',
    name: 'Trial Balance',
    path: '/finance/trial-balance',
    icon: FileSpreadsheet,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER', 'ACCOUNTS'],
    status: 'active',
    description: 'View trial balance reports',
    order: 10,
  },
  {
    id: 'journal-entries',
    name: 'Journal Entries',
    path: '/finance/journal-entries',
    icon: FileEdit,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Manage journal entries',
    order: 11,
  },
  {
    id: 'inter-company-reconciliation',
    name: 'Inter-Company Reconciliation',
    path: '/finance/inter-company-reconciliation',
    icon: Globe,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Reconcile inter-company transactions',
    order: 12,
  },
  {
    id: 'fixed-asset-register',
    name: 'Fixed Asset Register',
    path: '/finance/fixed-asset-register',
    icon: Briefcase,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Manage fixed assets',
    order: 13,
  },
  {
    id: 'tax-reports',
    name: 'Tax Reports',
    path: '/finance/tax-reports',
    icon: Receipt,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER', 'ACCOUNTS'],
    status: 'active',
    description: 'Generate tax reports',
    order: 14,
  },
  {
    id: 'bank-reconciliation',
    name: 'Bank Reconciliation',
    path: '/finance/bank-reconciliation',
    icon: Landmark,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['BANKER', 'ACCOUNTS', 'TREASURY'],
    status: 'active',
    description: 'Reconcile bank statements',
    order: 15,
  },
  {
    id: 'cash-flow-forecast',
    name: 'Cash Flow Forecast',
    path: '/finance/cash-flow-forecast',
    icon: TrendingUp,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'TREASURY'],
    status: 'active',
    description: 'Forecast cash flow',
    order: 16,
  },
  {
    id: 'payment-gateway',
    name: 'Payment Gateway',
    path: '/finance/payment-gateway-integration',
    icon: CreditCard,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['TREASURY', 'BANKER'],
    status: 'active',
    description: 'Manage payment integrations',
    order: 17,
  },
  {
    id: 'foreign-exchange',
    name: 'Foreign Exchange',
    path: '/finance/foreign-exchange-management',
    icon: Globe,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'TREASURY', 'BANKER'],
    status: 'active',
    description: 'Manage FX transactions',
    order: 18,
  },
  {
    id: 'loan-management',
    name: 'Loan Management',
    path: '/finance/loan-management',
    icon: Coins,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'TREASURY'],
    status: 'active',
    description: 'Track loans and financing',
    order: 19,
  },
  {
    id: 'chart-of-accounts',
    name: 'Chart of Accounts',
    path: '/finance/chart-of-accounts',
    icon: FolderOpen,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER', 'ACCOUNTS'],
    status: 'active',
    description: 'Manage account structure',
    order: 20,
  },
  {
    id: 'invoice-posting',
    name: 'Invoice Posting',
    path: '/finance/invoice-posting',
    icon: FileText,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS', 'ACCOUNTS PAYABLE'],
    status: 'active',
    description: 'Post and manage invoices',
    order: 21,
  },
  {
    id: 'period-adjustments',
    name: 'Period Adjustments',
    path: '/finance/period-end-adjustment-entries',
    icon: FileEdit,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['FINANCE CONTROLLER', 'ACCOUNTS'],
    status: 'active',
    description: 'Manage period adjustments',
    order: 22,
  },
  {
    id: 'purchase-invoice',
    name: 'Purchase Invoice',
    path: '/finance/purchase-invoice',
    icon: Receipt,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS PAYABLE', 'ACCOUNTS'],
    status: 'active',
    description: 'Process purchase invoices',
    order: 23,
  },
  {
    id: 'payment-entry',
    name: 'Payment Entry',
    path: '/finance/payment-entry',
    icon: Banknote,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS PAYABLE', 'TREASURY', 'BANKER'],
    status: 'active',
    description: 'Record payment transactions',
    order: 24,
  },
  {
    id: 'vendor-master',
    name: 'Vendor Master',
    path: '/finance/vendor-master',
    icon: Users,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS PAYABLE', 'PROCUREMENT OFFICER'],
    status: 'active',
    description: 'Manage vendor information',
    order: 25,
  },
  {
    id: 'expense-report',
    name: 'Expense Report',
    path: '/finance/expense-report',
    icon: Calculator,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Submit and track expenses',
    order: 26,
  },
  {
    id: 'payment-batch',
    name: 'Batch Processing',
    path: '/finance/payment-batch-processing',
    icon: Boxes,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['TREASURY', 'BANKER', 'ACCOUNTS PAYABLE'],
    status: 'active',
    description: 'Process payment batches',
    order: 27,
  },
  {
    id: 'payment-view',
    name: 'Payment View',
    path: '/finance/payment-entry-view',
    icon: FileText,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['ACCOUNTS', 'TREASURY'],
    status: 'active',
    description: 'View payment entries',
    order: 28,
  },
  {
    id: 'bank-upload',
    name: 'Bank Statement Upload',
    path: '/finance/bank-statement-upload',
    icon: Upload,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['BANKER', 'ACCOUNTS'],
    status: 'active',
    description: 'Upload bank statements',
    order: 29,
  },
  {
    id: 'bank-reconcile-exec',
    name: 'Execute Reconciliation',
    path: '/finance/bank-reconciliation-execute',
    icon: CheckCircle,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['BANKER', 'ACCOUNTS'],
    status: 'active',
    description: 'Execute bank reconciliation',
    order: 30,
  },
  {
    id: 'payment-approval',
    name: 'Payment Approval',
    path: '/finance/payment-approval-queue',
    icon: CheckCircle,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'TREASURY', 'FINANCE CONTROLLER'],
    status: 'active',
    description: 'Approve pending payments',
    order: 31,
  },
  {
    id: 'finance-about',
    name: 'About Me',
    path: '/finance/about-me',
    icon: Users,
    module: 'finance',
    permissions: ['executive-dashboard'],
    roles: ['CFO', 'FINANCE CONTROLLER', 'TREASURY', 'ACCOUNTS', 'ACCOUNTS PAYABLE', 'BANKER'],
    status: 'active',
    description: 'User profile',
    order: 99,
  },

  // ==================== PROCUREMENT MODULE (4 pages) ====================
  {
    id: 'purchase-order',
    name: 'Purchase Order',
    path: '/procurement/purchase-order',
    icon: ShoppingCart,
    module: 'procurement',
    permissions: ['purchase-order'],
    roles: ['PROCUREMENT OFFICER'],
    status: 'active',
    description: 'Manage purchase orders',
    order: 1,
  },
  {
    id: 'purchase-request',
    name: 'Purchase Request',
    path: '/procurement/purchase-request',
    icon: FileText,
    module: 'procurement',
    permissions: ['purchase-order'],
    roles: ['PROCUREMENT OFFICER', 'STORE INCHARGE'],
    status: 'active',
    description: 'Create and manage purchase requests',
    order: 2,
  },
  {
    id: 'supplier-quotation',
    name: 'Supplier Quotation',
    path: '/procurement/supplier-quotation',
    icon: FileText,
    module: 'procurement',
    permissions: ['purchase-order'],
    roles: ['PROCUREMENT OFFICER'],
    status: 'active',
    description: 'Manage supplier quotations',
    order: 3,
  },
  {
    id: 'supplier-master',
    name: 'Supplier Master',
    path: '/procurement/supplier-master',
    icon: Users,
    module: 'procurement',
    permissions: ['purchase-order'],
    roles: ['PROCUREMENT OFFICER'],
    status: 'active',
    description: 'Manage supplier database',
    order: 4,
  },
  {
    id: 'material-request',
    name: 'Material Request',
    path: '/procurement/material-request',
    icon: Package,
    module: 'procurement',
    permissions: ['purchase-order'],
    roles: ['PROCUREMENT OFFICER', 'STORE INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Create material requests',
    order: 5,
  },
  {
    id: 'procurement-about',
    name: 'About Me',
    path: '/procurement/about-me',
    icon: Users,
    module: 'procurement',
    permissions: ['purchase-order'],
    roles: ['PROCUREMENT OFFICER'],
    status: 'active',
    description: 'User profile',
    order: 99,
  },

  // ==================== OPERATIONS MODULE (12 pages) ====================
  {
    id: 'kpi-dashboard',
    name: 'KPI Dashboard',
    path: '/operations/kpi-dashboard',
    icon: BarChart3,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['OPERATIONS MANAGER', 'HUB INCHARGE'],
    status: 'active',
    description: 'Operations KPI overview',
    order: 1,
  },
  {
    id: 'stock-entry',
    name: 'Stock Entry',
    path: '/operations/stock-entry',
    icon: Package,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['STORE INCHARGE', 'HUB INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Record stock movements',
    order: 2,
  },
  {
    id: 'item-master',
    name: 'Item Master',
    path: '/operations/item-master-limited',
    icon: Tag,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['STORE INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Manage item catalog',
    order: 3,
  },
  {
    id: 'stock-ledger',
    name: 'Stock Ledger',
    path: '/operations/stock-ledger',
    icon: BookOpen,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['STORE INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'View stock ledger',
    order: 4,
  },
  {
    id: 'delivery-note',
    name: 'Delivery Note',
    path: '/operations/delivery-note',
    icon: Truck,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['HUB INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Manage delivery notes',
    order: 5,
  },
  {
    id: 'quality-inspection',
    name: 'Quality Inspection',
    path: '/operations/quality-inspection',
    icon: ClipboardCheck,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['STORE INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Perform quality checks',
    order: 6,
  },
  {
    id: 'sales-order',
    name: 'Sales Order',
    path: '/operations/sales-order',
    icon: ShoppingCart,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['HUB INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Manage sales orders',
    order: 7,
  },
  {
    id: 'work-order',
    name: 'Work Order',
    path: '/operations/work-order',
    icon: Factory,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['OPERATIONS MANAGER', 'HUB INCHARGE'],
    status: 'active',
    description: 'Create and track work orders',
    order: 8,
  },
  {
    id: 'bom-view',
    name: 'Bill of Materials',
    path: '/operations/bom-view',
    icon: ListChecks,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['OPERATIONS MANAGER', 'STORE INCHARGE'],
    status: 'active',
    description: 'View BOM structure',
    order: 9,
  },
  {
    id: 'shipping-logistics',
    name: 'Shipping & Logistics',
    path: '/operations/shipping-logistics',
    icon: Truck,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['HUB INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Manage shipping operations',
    order: 10,
  },
  {
    id: 'stock-transfer',
    name: 'Stock Transfer',
    path: '/operations/stock-entry-transfer',
    icon: MapPin,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['STORE INCHARGE', 'HUB INCHARGE'],
    status: 'active',
    description: 'Transfer stock between locations',
    order: 11,
  },
  {
    id: 'sales-order-view',
    name: 'Sales Order View',
    path: '/operations/sales-order-view',
    icon: FileText,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['HUB INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'View sales orders',
    order: 12,
  },
  {
    id: 'asset-register',
    name: 'Asset Register',
    path: '/operations/asset-register-hub',
    icon: Box,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['HUB INCHARGE', 'OPERATIONS MANAGER'],
    status: 'active',
    description: 'Manage hub assets',
    order: 13,
  },
  {
    id: 'operations-about',
    name: 'About Me',
    path: '/operations/about-me',
    icon: Users,
    module: 'operations',
    permissions: ['kpi-dashboard'],
    roles: ['OPERATIONS MANAGER', 'HUB INCHARGE', 'STORE INCHARGE'],
    status: 'active',
    description: 'User profile',
    order: 99,
  },

  // ==================== COMPLIANCE MODULE (8 pages) ====================
  {
    id: 'compliance-dashboard',
    name: 'Compliance Dashboard',
    path: '/compliance/compliance-dashboard',
    icon: Scale,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['COMPLIANCE', 'LEGAL'],
    status: 'active',
    description: 'Compliance overview',
    order: 1,
  },
  {
    id: 'audit-trail',
    name: 'Audit Trail',
    path: '/compliance/audit-trail',
    icon: Activity,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['COMPLIANCE', 'LEGAL'],
    status: 'active',
    description: 'View complete audit trail',
    order: 2,
  },
  {
    id: 'policy-management',
    name: 'Policy Management',
    path: '/compliance/policy-management',
    icon: FileCheck,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['COMPLIANCE', 'LEGAL'],
    status: 'active',
    description: 'Manage compliance policies',
    order: 3,
  },
  {
    id: 'regulatory-templates',
    name: 'Report Templates',
    path: '/compliance/regulatory-report-templates',
    icon: FileText,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['COMPLIANCE', 'LEGAL'],
    status: 'active',
    description: 'Manage regulatory templates',
    order: 4,
  },
  {
    id: 'approval-workflows',
    name: 'Approval Workflows',
    path: '/compliance/approval-workflow-view',
    icon: CheckCircle,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['COMPLIANCE'],
    status: 'active',
    description: 'View approval processes',
    order: 5,
  },
  {
    id: 'contract-management',
    name: 'Contract Management',
    path: '/compliance/contract-management',
    icon: FileSignature,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['LEGAL', 'COMPLIANCE'],
    status: 'active',
    description: 'Manage contracts',
    order: 6,
  },
  {
    id: 'litigation-tracker',
    name: 'Litigation Tracker',
    path: '/compliance/litigation-tracker',
    icon: Gavel,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['LEGAL'],
    status: 'active',
    description: 'Track legal cases',
    order: 7,
  },
  {
    id: 'document-repository',
    name: 'Document Repository',
    path: '/compliance/document-repository-view',
    icon: Folder,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['COMPLIANCE', 'LEGAL'],
    status: 'active',
    description: 'Access document library',
    order: 8,
  },
  {
    id: 'legal-master',
    name: 'Legal Master Data',
    path: '/compliance/vendor-customer-master-legal',
    icon: UserCheck,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['LEGAL', 'COMPLIANCE'],
    status: 'active',
    description: 'Manage legal entity data',
    order: 9,
  },
  {
    id: 'compliance-about',
    name: 'About Me',
    path: '/compliance/about-me',
    icon: Users,
    module: 'compliance',
    permissions: ['compliance-dashboard'],
    roles: ['COMPLIANCE', 'LEGAL'],
    status: 'active',
    description: 'User profile',
    order: 99,
  },
];

/**
 * Get pages for a specific module
 */
export function getPagesByModule(moduleId: string): PageMetadata[] {
  return PAGE_REGISTRY
    .filter(page => page.module === moduleId)
    .sort((a, b) => (a.order || 0) - (b.order || 0));
}

/**
 * Get pages accessible by a user's permissions
 */
export function getAccessiblePages(userPermissions: string[]): PageMetadata[] {
  return PAGE_REGISTRY.filter(page =>
    page.permissions.some(perm => userPermissions.includes(perm))
  );
}

/**
 * Get pages by role
 */
export function getPagesByRole(roleName: string): PageMetadata[] {
  const normalizedRole = roleName.toUpperCase();
  return PAGE_REGISTRY.filter(page =>
    page.roles.some(role => role.toUpperCase() === normalizedRole)
  );
}

/**
 * Check if a page exists (for route validation)
 */
export function pageExists(pageId: string): boolean {
  return PAGE_REGISTRY.some(page => page.id === pageId);
}

/**
 * Get page by path
 */
export function getPageByPath(path: string): PageMetadata | undefined {
  return PAGE_REGISTRY.find(page => page.path === path);
}

/**
 * Get navigation structure grouped by module
 */
export function getNavigationStructure(userPermissions: string[]): Record<string, PageMetadata[]> {
  const accessiblePages = getAccessiblePages(userPermissions);
  const grouped: Record<string, PageMetadata[]> = {};

  Object.keys(MODULES).forEach(moduleId => {
    grouped[moduleId] = accessiblePages
      .filter(page => page.module === moduleId)
      .sort((a, b) => (a.order || 0) - (b.order || 0));
  });

  return grouped;
}
