#!/bin/bash

# ============================================================================
# RATE LIMITING SETUP SCRIPT
# ============================================================================
# This script sets up advanced rate limiting for the BISMAN ERP backend
# Run this after creating the middleware and updating app.js
# ============================================================================

set -e  # Exit on error

echo "🛡️  BISMAN ERP - Rate Limiting Setup"
echo "===================================="
echo ""

# Check if we're in the correct directory
if [ ! -f "package.json" ]; then
  echo "❌ Error: package.json not found. Please run this script from my-backend directory."
  exit 1
fi

# Step 1: Install rate-limit-redis if not already installed
echo "📦 Step 1: Installing dependencies..."
if ! grep -q "rate-limit-redis" package.json; then
  echo "   Installing rate-limit-redis..."
  npm install rate-limit-redis --save
else
  echo "   ✅ rate-limit-redis already installed"
fi

# Step 2: Check if Redis is configured
echo ""
echo "🔍 Step 2: Checking Redis configuration..."
if grep -q "REDIS_URL" .env 2>/dev/null; then
  REDIS_URL=$(grep REDIS_URL .env | cut -d '=' -f2)
  echo "   ✅ Redis URL found in .env"
else
  echo "   ⚠️  Redis URL not found in .env"
  echo "   Rate limiting will use in-memory store (not recommended for production)"
  echo ""
  echo "   To use Redis, add to .env:"
  echo "   REDIS_URL=redis://default:password@your-redis-host:6379"
  echo ""
  read -p "   Do you want to continue without Redis? (y/n) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
fi

# Step 3: Run database migration
echo ""
echo "🗄️  Step 3: Running database migration..."
if [ -f "prisma/migrations/add_rate_limit_violations.sql" ]; then
  echo "   Found migration file"
  
  # Check if DATABASE_URL is set
  if grep -q "DATABASE_URL" .env 2>/dev/null; then
    echo "   Applying migration..."
    
    # Generate Prisma client first
    npx prisma generate
    
    # Run migration using psql if available, otherwise use Prisma
    if command -v psql &> /dev/null; then
      DATABASE_URL=$(grep DATABASE_URL .env | cut -d '=' -f2)
      psql "$DATABASE_URL" < prisma/migrations/add_rate_limit_violations.sql
      echo "   ✅ Migration applied via psql"
    else
      echo "   Note: psql not found. Please run migration manually:"
      echo "   psql \$DATABASE_URL < prisma/migrations/add_rate_limit_violations.sql"
    fi
    
    # Regenerate Prisma client with new model
    npx prisma generate
    echo "   ✅ Prisma client regenerated"
  else
    echo "   ⚠️  DATABASE_URL not found in .env"
    echo "   Please run migration manually after setting up database"
  fi
else
  echo "   ❌ Migration file not found at prisma/migrations/add_rate_limit_violations.sql"
  exit 1
fi

# Step 4: Update environment variables
echo ""
echo "⚙️  Step 4: Checking rate limit configuration..."

# Check if rate limit variables exist in .env
NEEDS_UPDATE=false

if ! grep -q "LOGIN_RATE_LIMIT" .env 2>/dev/null; then
  NEEDS_UPDATE=true
fi

if [ "$NEEDS_UPDATE" = true ]; then
  echo "   Adding rate limit configuration to .env..."
  cat >> .env << 'EOF'

# ============================================
# RATE LIMITING CONFIGURATION
# ============================================
# Generated by setup script - Adjust as needed

# Rate limit thresholds (requests per window)
LOGIN_RATE_LIMIT=5           # 5 login attempts per 15 minutes
AUTH_RATE_LIMIT=20           # 20 auth operations per 10 minutes
API_RATE_LIMIT=100           # 100 API calls per 5 minutes
PUBLIC_RATE_LIMIT=60         # 60 public requests per minute
EXPENSIVE_RATE_LIMIT=10      # 10 expensive operations per hour

# Whitelisted IPs (comma-separated, optional)
RATE_LIMIT_WHITELIST=127.0.0.1,::1

# Enable detailed rate limit logging
DEBUG_RATE_LIMIT=0
EOF
  echo "   ✅ Rate limit configuration added to .env"
else
  echo "   ✅ Rate limit configuration already exists in .env"
fi

# Step 5: Verify middleware file
echo ""
echo "📁 Step 5: Verifying middleware files..."
if [ -f "middleware/advancedRateLimiter.js" ]; then
  echo "   ✅ advancedRateLimiter.js found"
else
  echo "   ❌ middleware/advancedRateLimiter.js not found"
  echo "   Please create this file from the provided template"
  exit 1
fi

# Step 6: Test Redis connection (if configured)
echo ""
echo "🔌 Step 6: Testing Redis connection..."
if grep -q "REDIS_URL" .env 2>/dev/null; then
  node -e "
    const Redis = require('ioredis');
    const redis = new Redis(process.env.REDIS_URL, {
      enableOfflineQueue: false,
      maxRetriesPerRequest: 3,
      connectTimeout: 5000
    });
    
    redis.ping()
      .then(() => {
        console.log('   ✅ Redis connection successful');
        redis.disconnect();
        process.exit(0);
      })
      .catch((err) => {
        console.log('   ⚠️  Redis connection failed:', err.message);
        console.log('   Rate limiting will use in-memory store');
        redis.disconnect();
        process.exit(0);
      });
  " 2>/dev/null || echo "   ⚠️  Could not test Redis connection"
else
  echo "   ⏭️  Skipping (no REDIS_URL configured)"
fi

# Step 7: Create test script
echo ""
echo "🧪 Step 7: Creating test script..."
cat > test-rate-limits.sh << 'EOF'
#!/bin/bash

# Test Rate Limiting Configuration
# Run this script to verify rate limits are working correctly

BASE_URL="${1:-http://localhost:3001}"
echo "Testing rate limits on: $BASE_URL"
echo "=================================="

# Test 1: Login rate limit (should block after 5 attempts)
echo ""
echo "Test 1: Login Rate Limit (5 attempts per 15 minutes)"
echo "Expected: First 5 attempts get 401, then 429"
for i in {1..7}; do
  STATUS=$(curl -X POST "$BASE_URL/api/auth/login" \
    -H "Content-Type: application/json" \
    -d '{"email":"test@test.com","password":"wrong"}' \
    -s -o /dev/null -w "%{http_code}")
  echo "  Attempt $i: HTTP $STATUS"
  sleep 0.5
done

# Test 2: API rate limit
echo ""
echo "Test 2: API Rate Limit (100 requests per 5 minutes)"
echo "Sending 105 requests quickly..."
BLOCKED=0
SUCCESS=0
for i in {1..105}; do
  STATUS=$(curl -X GET "$BASE_URL/api/health" \
    -s -o /dev/null -w "%{http_code}")
  if [ "$STATUS" = "429" ]; then
    BLOCKED=$((BLOCKED + 1))
  else
    SUCCESS=$((SUCCESS + 1))
  fi
done
echo "  Success: $SUCCESS, Blocked: $BLOCKED"

# Test 3: Check rate limit headers
echo ""
echo "Test 3: Rate Limit Headers"
curl -X GET "$BASE_URL/api/health" -I -s | grep -i "ratelimit"

echo ""
echo "✅ Rate limit tests complete"
echo ""
echo "To view violations:"
echo "  Query: SELECT * FROM rate_limit_violations ORDER BY timestamp DESC LIMIT 10;"
EOF

chmod +x test-rate-limits.sh
echo "   ✅ Test script created: test-rate-limits.sh"

# Step 8: Summary
echo ""
echo "=================================="
echo "✅ Setup Complete!"
echo "=================================="
echo ""
echo "Next Steps:"
echo ""
echo "1. Update app.js to use new rate limiters"
echo "   See: RATE_LIMITING_IMPLEMENTATION_GUIDE.md"
echo ""
echo "2. Apply rate limiters to auth routes"
echo "   File: routes/auth.js"
echo ""
echo "3. Configure Cloudflare rules"
echo "   See: CLOUDFLARE_RATE_LIMITING_QUICK_SETUP.md"
echo ""
echo "4. Test rate limits:"
echo "   ./test-rate-limits.sh"
echo ""
echo "5. Monitor violations:"
echo "   - Check logs in console"
echo "   - Query: SELECT * FROM rate_limit_violations;"
echo "   - Access: GET /api/admin/rate-limit-violations"
echo ""
echo "Configuration files:"
echo "  - Rate limits: .env (LOGIN_RATE_LIMIT, API_RATE_LIMIT, etc.)"
echo "  - Redis: .env (REDIS_URL)"
echo "  - Middleware: middleware/advancedRateLimiter.js"
echo ""
echo "Documentation:"
echo "  - Full guide: RATE_LIMITING_IMPLEMENTATION_GUIDE.md"
echo "  - Cloudflare: CLOUDFLARE_RATE_LIMITING_QUICK_SETUP.md"
echo ""

# Optional: Offer to restart server
read -p "Do you want to restart the server now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo "Restarting server..."
  npm run dev &
  echo "✅ Server started in background"
  echo "   Check logs with: tail -f logs/server.log"
fi

echo ""
echo "🛡️  Rate limiting setup complete!"
