name: Generate Living Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Docs generation skipped
        run: |
          echo "Docs python toolchain removed from repository; docs generation is skipped in CI."
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: living-docs-build
          path: |
            system-docs-site
            system-docs/artifacts
